# Generated by Django 5.2.1 on 2025-05-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoPortada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('beneficio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'elemento_portada',
            },
        ),
        migrations.CreateModel(
            name='FuncionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_avanzada', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'funcion_adicional',
            },
        ),
        migrations.CreateModel(
            name='PaginaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'pagina_basica',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='Tipouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipouser',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.IntegerField()),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('funciones_obligatorias', models.ManyToManyField(blank=True, to='app.funcionadicional')),
                ('paginas', models.ManyToManyField(blank=True, to='app.paginabasica')),
                ('secciones', models.ManyToManyField(blank=True, to='app.elementoportada')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='paginabasica',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='paginas_basicas', to='app.producto'),
        ),
        migrations.CreateModel(
            name='Mensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'mensual',
            },
        ),
        migrations.AddField(
            model_name='funcionadicional',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='funciones_adicionales', to='app.producto'),
        ),
        migrations.AddField(
            model_name='elementoportada',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='elementos', to='app.producto'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('seguridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.preguntas')),
                ('tipoUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipouser')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
