# Generated by Django 5.2.1 on 2025-05-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='app.preguntas')),
            ],
            options={
                'db_table': 'respuestas',
            },
        ),
    ]
