# Generated by Django 5.2.1 on 2025-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_password_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='seguridad',
        ),
        migrations.AddField(
            model_name='users',
            name='seguridad',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='app.preguntas'),
        ),
    ]
