# Generated by Django 5.2.1 on 2025-05-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_users_seguridad_users_seguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_trabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais'),
        ),
    ]
