# Generated by Django 5.2.1 on 2025-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_beneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('beneficios', models.ManyToManyField(related_name='tipos', to='app.beneficio')),
            ],
        ),
    ]
