# Generated by Django 5.2.1 on 2025-05-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tipobeneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeBeneficioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('puntaje', models.PositiveIntegerField()),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beneficio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'puntaje_beneficio_producto',
                'unique_together': {('beneficio', 'producto', 'categoria')},
            },
        ),
    ]
