# Generated by Django 5.2.1 on 2025-05-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_puntajebeneficioproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntajebeneficioproducto',
            options={'verbose_name': 'Puntaje de Beneficio por Producto', 'verbose_name_plural': 'Puntajes de Beneficios por Producto'},
        ),
    ]
