# Generated by Django 5.2.1 on 2025-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_puntajebeneficioproducto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='maxPaginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='maxSecciones',
            field=models.IntegerField(default=0),
        ),
    ]
