# Generated by Django 5.2.1 on 2025-06-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producto_maxpaginas_producto_maxsecciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='CustomUser',
        ),
    ]
