# Generated by Django 5.2.1 on 2025-06-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_producto_maxpaginas_producto_maxsecciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensual",
            name="producto",
            field=models.CharField(max_length=255),
        ),
    ]
