# Generated by Django 5.2.1 on 2025-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_mensual_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficio",
            name="elementos_portada",
            field=models.ManyToManyField(
                blank=True, related_name="beneficios", to="app.elementoportada"
            ),
        ),
        migrations.AddField(
            model_name="beneficio",
            name="funciones_adicionales",
            field=models.ManyToManyField(
                blank=True, related_name="beneficios", to="app.funcionadicional"
            ),
        ),
        migrations.AddField(
            model_name="beneficio",
            name="paginas_basicas",
            field=models.ManyToManyField(
                blank=True, related_name="beneficios", to="app.paginabasica"
            ),
        ),
    ]
