# Generated by Django 5.2.1 on 2025-06-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_beneficio_elementos_portada_and_more"),
        ("app", "0014_alter_customuser_managers_and_more"),
    ]

    operations = []
