# Generated by Django 5.2.1 on 2025-06-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_merge_20250619_1202"),
        ("app", "0015_passwordresettoken"),
    ]

    operations = []
