# Generated by Django 5.2.1 on 2025-09-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_googletoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('document_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('correo_compartido', models.EmailField(max_length=254)),
                ('cliente', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to='app.customuser')),
            ],
        ),
    ]
