# Generated by Django 5.2.1 on 2025-09-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customuser_pais_alter_customuser_tipouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipoUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipouser'),
        ),
    ]
