# Generated by Django 5.2.1 on 2025-09-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_documento_monto_alter_customuser_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='elementos_portada',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='funciones_adicionales',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='paginas_basicas',
        ),
        migrations.AddField(
            model_name='funcionadicional',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funciones_adicionales', to='app.beneficio'),
        ),
        migrations.AddField(
            model_name='paginabasica',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paginas_basicas', to='app.beneficio'),
        ),
        migrations.AlterField(
            model_name='elementoportada',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementos_portada', to='app.beneficio'),
        ),
    ]
