# Generated by Django 5.2.1 on 2025-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_beneficio_elementos_portada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionadicional',
            name='beneficio',
        ),
        migrations.RemoveField(
            model_name='paginabasica',
            name='beneficio',
        ),
        migrations.AddField(
            model_name='beneficio',
            name='elementos_portada',
            field=models.ManyToManyField(blank=True, related_name='beneficios', to='app.elementoportada'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='funciones_adicionales',
            field=models.ManyToManyField(blank=True, related_name='beneficios', to='app.funcionadicional'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='paginas_basicas',
            field=models.ManyToManyField(blank=True, related_name='beneficios', to='app.paginabasica'),
        ),
        migrations.AlterField(
            model_name='elementoportada',
            name='beneficio',
            field=models.CharField(max_length=255),
        ),
    ]
