# Generated by Django 5.2.1 on 2025-09-18 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_funcionadicional_beneficio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='elementos_portada',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='funciones_adicionales',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='paginas_basicas',
        ),
        migrations.AddField(
            model_name='beneficio',
            name='elemento_portada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficio_elemento', to='app.elementoportada'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='funcion_adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficio_funcion', to='app.funcionadicional'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='pagina_basica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficio_pagina', to='app.paginabasica'),
        ),
    ]
