# Generated by Django 5.2.1 on 2025-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_beneficio_elementos_portada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='elemento_portada',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='funcion_adicional',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='pagina_basica',
        ),
        migrations.AddField(
            model_name='beneficio',
            name='elementos_portada',
            field=models.ManyToManyField(blank=True, related_name='beneficios', to='app.elementoportada'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='funciones_adicionales',
            field=models.ManyToManyField(blank=True, related_name='beneficios', to='app.funcionadicional'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='paginas_basicas',
            field=models.ManyToManyField(blank=True, related_name='beneficios', to='app.paginabasica'),
        ),
    ]
